// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: scan_telemetry.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRecentTelemetrySummaries = `-- name: GetRecentTelemetrySummaries :many
SELECT sth.analysis_id, da.ascii_domain, sth.total_duration_ms, sth.phase_count, sth.sha3_512, sth.created_at
FROM scan_telemetry_hash sth
JOIN domain_analyses da ON da.id = sth.analysis_id
ORDER BY sth.created_at DESC
LIMIT $1
`

type GetRecentTelemetrySummariesRow struct {
	AnalysisID      int32            `db:"analysis_id" json:"analysis_id"`
	AsciiDomain     string           `db:"ascii_domain" json:"ascii_domain"`
	TotalDurationMs int32            `db:"total_duration_ms" json:"total_duration_ms"`
	PhaseCount      int32            `db:"phase_count" json:"phase_count"`
	Sha3512         string           `db:"sha3_512" json:"sha3_512"`
	CreatedAt       pgtype.Timestamp `db:"created_at" json:"created_at"`
}

func (q *Queries) GetRecentTelemetrySummaries(ctx context.Context, limit int32) ([]GetRecentTelemetrySummariesRow, error) {
	rows, err := q.db.Query(ctx, getRecentTelemetrySummaries, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecentTelemetrySummariesRow{}
	for rows.Next() {
		var i GetRecentTelemetrySummariesRow
		if err := rows.Scan(
			&i.AnalysisID,
			&i.AsciiDomain,
			&i.TotalDurationMs,
			&i.PhaseCount,
			&i.Sha3512,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSlowestPhases = `-- name: GetSlowestPhases :many
SELECT phase_group, phase_task, AVG(duration_ms)::INT AS avg_ms,
       PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY duration_ms)::INT AS p50_ms,
       PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY duration_ms)::INT AS p95_ms,
       PERCENTILE_CONT(0.99) WITHIN GROUP (ORDER BY duration_ms)::INT AS p99_ms,
       COUNT(*) AS sample_count
FROM scan_phase_telemetry
WHERE created_at >= NOW() - INTERVAL '7 days'
GROUP BY phase_group, phase_task
ORDER BY p95_ms DESC
LIMIT $1
`

type GetSlowestPhasesRow struct {
	PhaseGroup  string `db:"phase_group" json:"phase_group"`
	PhaseTask   string `db:"phase_task" json:"phase_task"`
	AvgMs       int32  `db:"avg_ms" json:"avg_ms"`
	P50Ms       int32  `db:"p50_ms" json:"p50_ms"`
	P95Ms       int32  `db:"p95_ms" json:"p95_ms"`
	P99Ms       int32  `db:"p99_ms" json:"p99_ms"`
	SampleCount int64  `db:"sample_count" json:"sample_count"`
}

func (q *Queries) GetSlowestPhases(ctx context.Context, limit int32) ([]GetSlowestPhasesRow, error) {
	rows, err := q.db.Query(ctx, getSlowestPhases, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSlowestPhasesRow{}
	for rows.Next() {
		var i GetSlowestPhasesRow
		if err := rows.Scan(
			&i.PhaseGroup,
			&i.PhaseTask,
			&i.AvgMs,
			&i.P50Ms,
			&i.P95Ms,
			&i.P99Ms,
			&i.SampleCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTelemetryByAnalysis = `-- name: GetTelemetryByAnalysis :many
SELECT id, analysis_id, phase_group, phase_task, started_at_ms, duration_ms, record_count, error, created_at
FROM scan_phase_telemetry
WHERE analysis_id = $1
ORDER BY started_at_ms, phase_task
`

func (q *Queries) GetTelemetryByAnalysis(ctx context.Context, analysisID int32) ([]ScanPhaseTelemetry, error) {
	rows, err := q.db.Query(ctx, getTelemetryByAnalysis, analysisID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanPhaseTelemetry{}
	for rows.Next() {
		var i ScanPhaseTelemetry
		if err := rows.Scan(
			&i.ID,
			&i.AnalysisID,
			&i.PhaseGroup,
			&i.PhaseTask,
			&i.StartedAtMs,
			&i.DurationMs,
			&i.RecordCount,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTelemetryHash = `-- name: GetTelemetryHash :one
SELECT analysis_id, total_duration_ms, phase_count, sha3_512, created_at
FROM scan_telemetry_hash
WHERE analysis_id = $1
`

func (q *Queries) GetTelemetryHash(ctx context.Context, analysisID int32) (ScanTelemetryHash, error) {
	row := q.db.QueryRow(ctx, getTelemetryHash, analysisID)
	var i ScanTelemetryHash
	err := row.Scan(
		&i.AnalysisID,
		&i.TotalDurationMs,
		&i.PhaseCount,
		&i.Sha3512,
		&i.CreatedAt,
	)
	return i, err
}

const getTelemetryTrends = `-- name: GetTelemetryTrends :many
SELECT spt.phase_group,
       DATE(spt.created_at) AS trend_date,
       AVG(spt.duration_ms)::INT AS avg_duration_ms,
       COUNT(*) AS sample_count
FROM scan_phase_telemetry spt
WHERE spt.created_at >= NOW() - INTERVAL '7 days'
GROUP BY spt.phase_group, DATE(spt.created_at)
ORDER BY trend_date, spt.phase_group
`

type GetTelemetryTrendsRow struct {
	PhaseGroup    string      `db:"phase_group" json:"phase_group"`
	TrendDate     pgtype.Date `db:"trend_date" json:"trend_date"`
	AvgDurationMs int32       `db:"avg_duration_ms" json:"avg_duration_ms"`
	SampleCount   int64       `db:"sample_count" json:"sample_count"`
}

func (q *Queries) GetTelemetryTrends(ctx context.Context) ([]GetTelemetryTrendsRow, error) {
	rows, err := q.db.Query(ctx, getTelemetryTrends)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTelemetryTrendsRow{}
	for rows.Next() {
		var i GetTelemetryTrendsRow
		if err := rows.Scan(
			&i.PhaseGroup,
			&i.TrendDate,
			&i.AvgDurationMs,
			&i.SampleCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPhaseTelemetry = `-- name: InsertPhaseTelemetry :exec
INSERT INTO scan_phase_telemetry (analysis_id, phase_group, phase_task, started_at_ms, duration_ms, record_count, error)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertPhaseTelemetryParams struct {
	AnalysisID  int32   `db:"analysis_id" json:"analysis_id"`
	PhaseGroup  string  `db:"phase_group" json:"phase_group"`
	PhaseTask   string  `db:"phase_task" json:"phase_task"`
	StartedAtMs int32   `db:"started_at_ms" json:"started_at_ms"`
	DurationMs  int32   `db:"duration_ms" json:"duration_ms"`
	RecordCount *int32  `db:"record_count" json:"record_count"`
	Error       *string `db:"error" json:"error"`
}

func (q *Queries) InsertPhaseTelemetry(ctx context.Context, arg InsertPhaseTelemetryParams) error {
	_, err := q.db.Exec(ctx, insertPhaseTelemetry,
		arg.AnalysisID,
		arg.PhaseGroup,
		arg.PhaseTask,
		arg.StartedAtMs,
		arg.DurationMs,
		arg.RecordCount,
		arg.Error,
	)
	return err
}

const insertTelemetryHash = `-- name: InsertTelemetryHash :exec
INSERT INTO scan_telemetry_hash (analysis_id, total_duration_ms, phase_count, sha3_512)
VALUES ($1, $2, $3, $4)
`

type InsertTelemetryHashParams struct {
	AnalysisID      int32  `db:"analysis_id" json:"analysis_id"`
	TotalDurationMs int32  `db:"total_duration_ms" json:"total_duration_ms"`
	PhaseCount      int32  `db:"phase_count" json:"phase_count"`
	Sha3512         string `db:"sha3_512" json:"sha3_512"`
}

func (q *Queries) InsertTelemetryHash(ctx context.Context, arg InsertTelemetryHashParams) error {
	_, err := q.db.Exec(ctx, insertTelemetryHash,
		arg.AnalysisID,
		arg.TotalDurationMs,
		arg.PhaseCount,
		arg.Sha3512,
	)
	return err
}
